language: php

cache:
  directories:
    - node_modules

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - hhvm
  - nightly

sudo: false

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm
    - php: nightly

before_install:
  - if [[ $TRAVIS_PHP_VERSION != 'hhvm' && $TRAVIS_PHP_VERSION < 'nightly' ]]; then phpenv config-rm xdebug.ini; fi
#  - travis_retry composer self-update
#  - travis_retry composer dump-autoload --no-dev

before_script:
  - composer install --no-progress --prefer-source

script:
  - vendor/bin/phpunit
